version: '3.9'

x-restart-policy: &restart_policy
  restart: unless-stopped

x-logging: &logging
  logging:
    options:
      max-file: '5'
      max-size: '10m'

services:
  postgres:
    <<: *logging
    <<: *restart_policy
    build: ./postgresql
    container_name: postgres
    environment:
      - POSTGRES_USER=expectopatronum
      - POSTGRES_PASSWORD=expectopatronum
      - POSTGRES_DB=expectopatronum
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - expecto_patronum:/var/lib/postgresql/data
    networks:
      - expecto_patronum

  redis:
    <<: *logging
    <<: *restart_policy
    image: 'redis:6.2.6-alpine'
    container_name: redis
    command: 'redis-server --requirepass redis --loglevel warning'
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      - expecto_patronum

  bot:
    <<: *logging
    <<: *restart_policy
    image: ghcr.io/r-priyam/expecto-patronum:latest
    container_name: expecto_patronum
    env_file:
      - ../.env
    networks:
      - expecto_patronum
    depends_on:
      - postgres
      - redis
    tty: true

volumes:
  expecto_patronum:

networks:
  expecto_patronum:
